fix base url value
This is the behavior : 
>>> from pycvesearch import CVESearch
>>> cve = CVESearch()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'base_url'
>>> 
Otherwise please change the wiki to initialize as follow:
>>> cve = CVESearch('https://cve.circl.lu/')